FROM python:alpine

COPY ./sortomatic /code
WORKDIR /code
EXPOSE 8080

COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install -e /code

CMD ["sortomatic", "gui", "data/input", "--cache", "/cache"]
